IF OBJECT_ID ('nome_objeto', 'tipo_objeto') IS NOT NULL

--AND TYPE ='FN'	--SQL_SCALAR_FUNCTION
--AND TYPE ='IF'    --SQL_INLINE_TABLE_VALUED_FUNCTION
--AND TYPE ='UQ'	--UNIQUE_CONSTRAINT
--AND TYPE ='SQ'	--SERVICE_QUEUE
--AND TYPE ='F' 	--FOREIGN_KEY_CONSTRAINT
--AND TYPE ='U' 	--USER_TABLE
--AND TYPE ='D' 	--DEFAULT_CONSTRAINT
--AND TYPE ='PK'	--PRIMARY_KEY_CONSTRAINT
--AND TYPE ='V' 	--VIEW
--AND TYPE ='S' 	--SYSTEM_TABLE
--AND TYPE ='IT'	--INTERNAL_TABLE
--AND TYPE ='P' 	--SQL_STORED_PROCEDURE
--AND TYPE ='TF'	--SQL_TABLE_VALUED_FUNCTION