/*LIMPA BASE SA*/
DELETE Historico_WorkFlow
DELETE Riscos_Matriz_Ciclos
DELETE Pontos_Auditoria_PlanosAcao
DELETE PlanosAcao_Estrutura_ORG
DELETE Pontos_Auditoria 
DELETE Riscos_Matriz_Ciclos 
DELETE PlanosAcao_Etapa
DELETE Riscos_PlanosAcao
DELETE Riscos_Causas
DELETE Controles_CAVRsControles
DELETE Controles_Assertivas
DELETE Controles_TiposControles
DELETE Controles_Deficiencias
DELETE Controles_Testes_Agenda
DELETE Testes_Execucoes_Arquivos
DELETE Controles_Testes_Execucoes
DELETE Controles_Testes
DELETE Atividades_Riscos_Controles
DELETE Riscos_Controles
DELETE Riscos_Consequencias
DELETE Riscos_Eventos
DELETE Riscos_Matriz
DELETE Riscos_Causas   
DELETE Riscos_PlanosAcao  
DELETE Riscos
DELETE Matriz_Blindagens
DELETE [Matriz]
DELETE Atividades_Antecessoras
DELETE Atividades_Sistemas
DELETE Atividades_Riscos_Controles
DELETE Atividades
DELETE SubProcessos_Antecessores  
DELETE SubProcessos_Grupos
DELETE SubProcesso_Funcionario
DELETE SubProcesso_Funcionario_Grupos
DELETE SubProcessos
DELETE Processos_Produtos
DELETE Processos_Politicas
DELETE Processos_Funcionarios_Grupos
DELETE Processos_Funcionarios
DELETE Processos_Legislacao
DELETE Processos_Grupos
DELETE [Processos]
DELETE Questionarios_Ciclos
DELETE [Matriz_Ciclos_Estrutura_ORG_TA]
DELETE [Matriz_Ciclos]
DELETE Questionarios_Aplicacoes_Respostas 
DELETE Riscos_Causas   
DELETE Questionarios_Ciclos 
DELETE Questionarios_Aplicacoes
DELETE TWorkFlowAcaoLog 
DELETE Matriz_Ciclos_Estrutura_ORG_TA
/*LIMPA BASE RESTANTE*/
delete  Assertivas
delete  Assertivas_Log
delete  Atividades_Antecessoras_Log
delete  Atividades_Arquivos
delete  Atividades_Arquivos_Log
delete  Atividades_Log
delete  Atividades_Riscos_Controles_Log
delete  Atividades_Sistemas_Log
delete  Avaliacao_Controle_Criticidade
delete  Avaliacao_Qualitativa_Quantitativa
delete  Ciclos
delete  Ciclos_Log
delete  ClassificacaoCoso
delete  Consequencias_Status
delete  Consequencias_Status_Log
delete  Controles_Assertivas_Log
delete  Controles_Avaliacoes
delete  Controles_Avaliacoes_Log
delete  Controles_CAVRs
delete  Controles_CAVRs_Log
delete  Controles_CAVRsControles_Log
delete  Controles_Deficiencias_Log
delete  Controles_Modos
delete  Controles_Modos_Log
delete  Controles_Naturezas
delete  Controles_Naturezas_Log
delete  Controles_Objetivos
delete  Controles_Objetivos_Log
delete  Controles_Testes_Agenda_Log
delete  Controles_Testes_Execucoes_Log
delete  Controles_Testes_Log
delete  Controles_Tipos
delete  Controles_Tipos_CosoComponentes
delete  Controles_Tipos_CosoComponentes_Log
delete  Controles_Tipos_Log
delete  Controles_TiposControles_Log
delete  CosoComponentes
delete  CosoComponentes_Log
delete  Criticidades
delete  Deficiencias_Status
delete  Deficiencias_Status_Log
delete  Email
delete  EscalaFrequencia
delete  EscalaValorImpacto
delete  Estrutura_ORG_TA
delete  Estrutura_ORG_TA_Log
delete  Estrutura_Org_Tipos
delete  Estrutura_Org_Tipos_Log
delete  FrequenciaImpacto
delete  ImpactoFinanceiro
delete  ImpactoFinanceiroEscala
delete  Legislacao
delete  Legislacao_Log
delete  Matriz_Blindagens_Log
delete  Matriz_Ciclos_Estrutura_ORG_TA_Log
delete  Matriz_Ciclos_Log
delete  Matriz_Empresas
delete  Matriz_Empresas_Log
delete  Matriz_Log
delete  Matriz_Tipos
delete  Matriz_Tipos_Log
delete  Niveis
delete  PlanosAcao_Comentario
delete  PlanosAcao_Estrutura_ORG_Log
delete  PlanosAcao_Etapa_Log
delete  PlanosAcao_Status
delete  PlanosAcao_Status_Log
delete  Politicas
delete  Politicas_Log
delete  Pontos_Auditoria_Datas_Limite
delete  Pontos_Auditoria_Log
delete  Pontos_Auditoria_PlanosAcao_Log
delete  PontosAuditoria_Motivos
delete  PontosAuditoria_Motivos_Log
delete  PontosAuditoria_Origens
delete  PontosAuditoria_Origens_Log
delete  PontosAuditoria_Status
delete  PontosAuditoria_Status_Log
delete  Processos_Funcionarios_Log
delete  Processos_Legislacao_Log
delete  Processos_Log
delete  Processos_Politicas_Log
delete  Processos_Produtos_Log
delete  Processos_Tipos
delete  Processos_Tipos_Log
delete  Produtos
delete  Questionarios
delete  Questionarios_AjusteFino_Perguntas
delete  Questionarios_AjusteFino_Perguntas_Log
delete  Questionarios_AjusteFino_Perguntas_TMP
delete  Questionarios_AjusteFino_Respostas
delete  Questionarios_AjusteFino_Respostas_Log
delete  Questionarios_AjusteFino_Respostas_TMP
delete  Questionarios_Aplicacoes_Log
delete  Questionarios_Aplicacoes_Respostas_Log
delete  Questionarios_Ciclos_Grupos
delete  Questionarios_Ciclos_Grupos_Log
delete  Questionarios_Ciclos_Log
delete  Questionarios_Grupos
delete  Questionarios_Grupos_Log
delete  Questionarios_Log
delete  Questionarios_Perguntas
delete  Questionarios_Perguntas_Log
delete  Questionarios_Perguntas_TMP
delete  Questionarios_Respostas
delete  Questionarios_Respostas_Log
delete  Questionarios_Respostas_TMP
delete  QuestionariosTipo
delete  QuestionariosTipo_Log
delete  RelacAnaliseRisco
delete  Riscos_Causas_Log
delete  Riscos_Consequencias_FollowUp_Acoes_Log
delete  Riscos_Consequencias_Log
delete  Riscos_Controles_Log
delete  Riscos_Eventos_Log
delete  Riscos_Funcionarios
delete  Riscos_Funcionarios_Log
delete  Riscos_Log
delete  Riscos_Matriz_Log
delete  Riscos_PlanosAcao_Log
delete  Riscos_Tratamentos
delete  Riscos_Tratamentos_Log
delete  Selecao_Justificativa
delete  Selecao_Justificativa_Log
delete  Semaforo
delete  Semaforo_Log
delete  Shapes
delete  Shapes_Log
delete  StatusRegistro
delete  SubProcesso_Funcionario_Log
delete  SubProcesso_Funcionario_Tipos_Log
delete  SubProcessos_Antecessores_Log
delete  SubProcessos_ContasCosifs
delete  SubProcessos_ContasCosifs_Log
delete  SubProcessos_ContasCosifs_TMP
delete  SubProcessos_Empresas
delete  SubProcessos_Empresas_Log
delete  SubProcessos_Funcionarios_Tipos_WorkFlow_Caracteristicas
delete  SubProcessos_Funcionarios_Tipos_WorkFlow_Caracteristicas_Log
delete  SubProcessos_Log
delete  TaxaConversaoMoeda
delete  tempFlowChartData
delete  Testes_Proprietarios
delete  Testes_Proprietarios_Log
delete  Testes_Resultados
delete  Testes_Resultados_Log
delete  Testes_Tipos
delete  Testes_Tipos_Log
delete  TFollowUpItem
delete  TFollowUpLogEnvio
delete  TFollowUpParametro
delete  TFollowUpTemplate
delete  TFollowUpTipo
delete  TipoAnaliseRisco
delete  TipoImpactoFinanceiro
delete  Tipologia_Risco
delete  TipoMoeda
delete  Tipos_Avaliacao
delete  Tipos_Avaliacao_Log
delete  Tipos_Selecao
delete  Tipos_Selecao_Log
delete  TipoValorPerda
delete  Tmp_Rel_Estagio
delete  TProjeto
delete  TProjetoGap
delete  TProjetoItem
delete  TProjetoSub
delete  TProjetoTarefa
delete  TProjetoTarefaStatus
delete  TProjetoTarefaStatus_Log
delete  TProjetoTarefaStatusTipo
delete  Unidades_Frequencia
delete  Unidades_Frequencia_Log